[package]
name = "palisade-client"
description = "Ergonomic Palisade client SDK: direct backend or gRPC transport"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
palisade-core.workspace = true
palisade-proto.workspace = true
tonic.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
async-trait.workspace = true

[dev-dependencies]
palisade-redis.workspace = true
palisade-server.workspace = true
redis.workspace = true
rcgen.workspace = true
