use std::fmt;

/// A monotonically increasing token returned with every successful lock grant.
///
/// Fencing tokens close the one hole lease-based locking cannot fix at the
/// lock layer alone: a holder that pauses past its TTL (GC stop, SIGSTOP,
/// VM migration) resumes believing it still holds the lock while another
/// owner has already acquired it. The protected resource compares tokens
/// and rejects any operation whose fence is not newer than the last one
/// it accepted.
///
/// Tokens are allocated by the storage backend (atomically with the grant)
/// and must never be generated by clients.
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
pub struct FencingToken(u64);

impl FencingToken {
    /// The sentinel used when no lock has ever been granted (fence 0).
    pub const ZERO: Self = Self(0);

    /// Creates a token from a raw counter value (backend use only).
    pub fn new(value: u64) -> Self {
        Self(value)
    }

    /// Raw counter value.
    pub const fn value(self) -> u64 {
        self.0
    }

    /// Returns `true` if this token is strictly newer than `last_seen`,
    /// i.e. the fenced operation may proceed.
    pub const fn supersedes(self, last_seen: Self) -> bool {
        self.0 > last_seen.0
    }
}

impl fmt::Display for FencingToken {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "fence#{}", self.0)
    }
}

impl fmt::Debug for FencingToken {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "FencingToken({})", self.0)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ordering_is_strict() {
        let a = FencingToken::new(1);
        let b = FencingToken::new(2);
        assert!(b > a);
        assert!(a.supersedes(FencingToken::ZERO));
        assert!(!a.supersedes(a));
    }

    #[test]
    fn zero_is_the_floor() {
        assert_eq!(FencingToken::ZERO.value(), 0);
        assert!(!FencingToken::ZERO.supersedes(FencingToken::ZERO));
    }

    #[test]
    fn display_is_human_readable() {
        assert_eq!(FencingToken::new(7).to_string(), "fence#7");
    }
}
