apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-palisade-server
  labels:
    app.kubernetes.io/name: palisade-server
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: grpc
      port: {{ .Values.service.port }}
      targetPort: grpc
  selector:
    app.kubernetes.io/name: palisade-server
    app.kubernetes.io/instance: {{ .Release.Name }}
